"""Update notes relationship

Revision ID: 1d6dd36d8615
Revises: 4ed91c26301b
Create Date: 2024-06-09 21:15:58.181016

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1d6dd36d8615'
down_revision: Union[str, None] = '4ed91c26301b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
